"""PySCF agent nodes — RHF/DFT and CASSCF paths.

Pre-computation:
- rhf_dft: generate RHF/DFT Python script + rough slurm
- casscf: read fchk → select orbitals → generate CASSCF script + slurm

Post-computation:
- parse_output: parse SCF/CASSCF energy from PySCF log
- register_artifacts: surface results for downstream agents
"""
from contracts.pyscf_task import PySCFResult
from contracts.agent_task import Artifact, ArtifactStatus, TaskStatus


def _update_scratchpad(state, **kwargs) -> dict:
    return {"scratchpad": {**state.scratchpad, **kwargs}}


# ═══════════════════════════════════════════════════════════════════
# Pre-computation: RHF / DFT
# ═══════════════════════════════════════════════════════════════════

def generate_rhf_input(state) -> dict:
    """Generate PySCF RHF/DFT Python script.

    Produces a self-contained .py file that:
    - Builds molecule from geometry
    - Sets up SCF with specified basis/functional
    - Runs kernel() and prints energy

    TODO: computational scientist fills in actual geometry + template.
    """
    task = state.task
    params = task.params

    # Build a general PySCF RHF script template
    script = f'''"""PySCF {params.job_type} calculation — generated by Tower."""
from pyscf import gto, scf
'''
    if params.job_type in ("RDFT", "UDFT") and params.functional:
        script += f"from pyscf import dft\n"

    script += f'''
# --- Molecule definition ---
mol = gto.Mole()
mol.atom = ""\"# TODO: computational scientist provides geometry
# Example: N 0 0 0; N 0 0 1.1
""\"
mol.basis = "{params.basis}"
mol.charge = {params.charge}
mol.spin = {params.spin}
mol.build()

# --- SCF calculation ---
'''
    if params.job_type in ("RDFT", "UDFT"):
        script += f'''mf = dft.RKS(mol) if "{params.job_type}".startswith("R") else dft.UKS(mol)
mf.xc = "{params.functional or 'b3lyp'}"
'''
    elif params.job_type.startswith("U"):
        script += "mf = scf.UHF(mol)\n"
    else:
        script += "mf = scf.RHF(mol)\n"

    script += f'''
mf.kernel()

# --- Output ---
print(f"SCF converged: {{mf.converged}}")
print(f"E({{mf.__class__.__name__}}) = {{mf.e_tot:.8f}} Ha")
'''

    return {
        "node_history": state.node_history + ["generate_rhf_input"],
        **_update_scratchpad(state,
            py_script=script,
            py_path=f"jobs/{task.task_id}/{task.task_id}.py",
        ),
    }


# ═══════════════════════════════════════════════════════════════════
# Pre-computation: CASSCF
# ═══════════════════════════════════════════════════════════════════

def read_fchk(state) -> dict:
    """Read Gaussian checkpoint via ArtifactResolver."""
    return {
        "node_history": state.node_history + ["read_fchk"],
        **_update_scratchpad(state, fchk_read=True),
    }


def select_orbitals(state) -> dict:
    """Select active space orbitals."""
    return {
        "node_history": state.node_history + ["select_orbitals"],
        **_update_scratchpad(state, orbitals_selected=True),
    }


def generate_casscf_input(state) -> dict:
    """Generate PySCF CASSCF script."""
    task = state.task
    params = task.params

    script = f"""# PySCF CASSCF — generated by Tower
# Active space: {params.n_active_electrons}e, {params.n_active_orbitals}o
# TODO: computational scientist fills in geometry + CASSCF setup
"""
    return {
        "node_history": state.node_history + ["generate_casscf_input"],
        **_update_scratchpad(state,
            py_script=script,
            py_path=f"jobs/{task.task_id}/{task.task_id}_casscf.py",
        ),
    }


# ═══════════════════════════════════════════════════════════════════
# Pre-computation: Slurm (shared)
# ═══════════════════════════════════════════════════════════════════

def generate_slurm(state) -> dict:
    """Generate rough Slurm template for HPC refinement."""
    task = state.task
    params = task.params

    slurm = f"""#!/bin/bash
#SBATCH --job-name={task.task_id}
#SBATCH --mem={getattr(params, 'max_memory_mb', 8000)}
#SBATCH --cpus-per-task={getattr(params, 'nprocs', 8)}
#SBATCH --time=24:00:00
# ROUGH TEMPLATE — HPC agent refines partition/account/node constraints

python {state.scratchpad.get('py_path', f'jobs/{task.task_id}/run.py')} > jobs/{task.task_id}/pyscf.log 2>&1
"""

    return {
        "node_history": state.node_history + ["generate_slurm"],
        **_update_scratchpad(state,
            slurm_content=slurm,
            slurm_path=f"jobs/{task.task_id}/pyscf_rough.sh",
        ),
    }


# ═══════════════════════════════════════════════════════════════════
# Pre-computation: done
# ═══════════════════════════════════════════════════════════════════

def pre_done(state) -> dict:
    """Return generated artifacts to supervisor."""
    task_id = state.task_id

    return {
        "status": TaskStatus.DONE,
        "artifacts_out": [
            Artifact(artifact_id=f"{task_id}-script",
                     path=state.scratchpad["py_path"],
                     type="gjf",  # PySCF script = "gjf" for generic input
                     description="PySCF Python script",
                     producer_agent="pyscf", producer_task_id=task_id),
            Artifact(artifact_id=f"{task_id}-slurm",
                     path=state.scratchpad["slurm_path"],
                     type="slurm",
                     description="Rough Slurm template for HPC refinement",
                     producer_agent="pyscf", producer_task_id=task_id),
        ],
        "node_history": state.node_history + ["pre_done"],
    }


# ═══════════════════════════════════════════════════════════════════
# Post-computation: parse + register (shared)
# ═══════════════════════════════════════════════════════════════════

def read_output(state) -> dict:
    """Read PySCF output log from HPC execution."""
    log_id = ""
    for ref in state.task.artifacts_in:
        if ref.type in ("log",):
            log_id = ref.artifact_id

    return {
        "node_history": state.node_history + ["read_output"],
        **_update_scratchpad(state, log_artifact_id=log_id),
    }


def parse_energy(state) -> dict:
    """Parse SCF or CASSCF energy from PySCF log.

    Extracts:
    - E(RHF) / E(CASSCF) from output
    - Convergence status
    - Wall time

    TODO: computational scientist implements actual regex parsing.
    """
    params = state.task.params

    if params.job_type == "CASSCF":
        result = PySCFResult(casscf_energy=None, converged=True)
    else:
        result = PySCFResult(scf_energy=None, converged=True)

    return {
        "result_data": result,
        "node_history": state.node_history + ["parse_energy"],
    }


def register_artifacts(state) -> dict:
    """Surface HPC-produced artifacts for downstream or supervisor."""
    log_id = state.scratchpad.get("log_artifact_id", "")
    artifacts = []
    if log_id:
        artifacts.append(Artifact(
            artifact_id=log_id, path="", type="log",
            description="PySCF output log (HPC-produced)",
            producer_agent="pyscf", producer_task_id=state.task_id,
            status=ArtifactStatus.READY,
        ))

    return {
        "status": TaskStatus.DONE,
        "artifacts_out": artifacts,
        "node_history": state.node_history + ["register_artifacts"],
    }
