"""PySCF agent nodes — LLM-driven generation, parsing, and error correction.

Pre-computation:
    generate_input → generate_slurm → pre_done

Post-computation:
    read_output → parse_output → [success → register_artifacts]
                                [failure + retries<5 → fix_input → pre_done]
                                [failure + retries>=5 → NEEDS_HUMAN]

All prompts loaded from prompts/pyscf/*.md at module load time.
"""
import json
from pathlib import Path

from contracts.pyscf_task import PySCFResult
from contracts.agent_task import Artifact, ArtifactStatus, TaskStatus

_PROMPT_DIR = Path(__file__).resolve().parent.parent.parent / "prompts" / "pyscf"
MAX_RETRIES = 5


def _load_prompt(name: str) -> str:
    """Load a prompt template from prompts/pyscf/<name>.md."""
    path = _PROMPT_DIR / name
    if not path.exists():
        return ""
    return path.read_text()


PYSCF_GENERATE_PROMPT = _load_prompt("pyscf_generate.md")
PYSCF_PARSE_PROMPT = _load_prompt("pyscf_parse.md")
PYSCF_FIX_PROMPT = _load_prompt("pyscf_fix.md")


def _update_scratchpad(state, **kwargs) -> dict:
    return {"scratchpad": {**state.scratchpad, **kwargs}}


def _parse_json_response(text: str) -> dict:
    """Extract JSON from LLM response, handling markdown fences."""
    text = text.strip()
    if "```json" in text:
        text = text.split("```json")[1].split("```")[0]
    elif "```" in text:
        text = text.split("```")[1].split("```")[0]
    return json.loads(text)


# ═══════════════════════════════════════════════════════════════════
# Pre-computation: generate input
# ═══════════════════════════════════════════════════════════════════


def generate_input(state) -> dict:
    """Generate a complete PySCF script from the task description using LLM."""
    from langchain_core.messages import HumanMessage, SystemMessage
    from tower.llm import get_model

    task = state.task
    params = task.params

    task_id = state.task_id
    run_dir = task_id.rsplit("-", 1)[0] if "-" in task_id else task_id
    script_path = f"{run_dir}/{task_id}.py"
    log_path = f"{run_dir}/pyscf.log"

    prompt = PYSCF_GENERATE_PROMPT.format(
        task_description=params.task_description or task.goal,
        charge=params.charge,
        spin=params.spin,
        fchk_artifact_id=params.fchk_artifact_id or "none",
        script_path=f"{task_id}.py",
        log_path="pyscf.log",
    )

    try:
        model = get_model(temperature=0.0)
        response = model.invoke([
            SystemMessage(content=prompt),
            HumanMessage(content="Generate the PySCF script."),
        ])
        data = _parse_json_response(response.content)
        script = data.get("script", "")
        mol = data.get("mol", {})
        expected_outputs = data.get("expected_outputs", [])
        run_command = data.get("run_command", "")
        resources = data.get("resources", {})
    except Exception:
        script = _fallback_script(params, task)
        mol = {}
        expected_outputs = []
        run_command = ""
        resources = {}

    if not run_command:
        run_command = f"python -u {task_id}.py > pyscf.log 2>&1"

    return {
        "node_history": state.node_history + ["generate_input"],
        "status": TaskStatus.RUNNING,
        **_update_scratchpad(
            state,
            py_script=script,
            py_path=script_path,
            log_path=log_path,
            run_command=run_command,
            mol=mol,
            expected_outputs=expected_outputs,
            resources=resources,
        ),
    }


def _fallback_script(params, task) -> str:
    """Fallback template if LLM is unavailable."""
    task_description = getattr(params, "task_description", "") or task.goal
    return f'''"""PySCF script — generated by Tower (fallback)."""
# Task: {task_description}
# Charge: {params.charge}, Spin: {params.spin}
from pyscf import gto, scf

mol = gto.Mole()
mol.atom = """# TODO: provide geometry for: {task_description}"""
mol.basis = "def2-svp"
mol.charge = {params.charge}
mol.spin = {params.spin}
mol.verbose = 4
mol.build()

mf = scf.RHF(mol)
mf.kernel()

print("---TOWER_OUTPUT_START---")
print('{{"scf_energy": {{:.8f}}, "scf_converged": {{}}}}'.format(mf.e_tot, str(mf.converged).lower()))
print("---TOWER_OUTPUT_END---")
'''


# ═══════════════════════════════════════════════════════════════════
# Pre-computation: Slurm + done
# ═══════════════════════════════════════════════════════════════════


def generate_slurm(state) -> dict:
    """Generate rough Slurm template for HPC refinement."""
    task = state.task
    sp = state.scratchpad

    resources = sp.get("resources", {})
    omp = resources.get("omp_threads", 8)
    mem = resources.get("memory_mb", 8000)
    wall_h = resources.get("walltime_hours", 24)
    modules = resources.get("modules", [])
    partition_hint = resources.get("partition_hint", "cpu8")

    task_id = task.task_id
    run_dir = task_id.rsplit("-", 1)[0] if "-" in task_id else task_id

    module_lines = "\n".join(f"module load {m}" for m in modules)
    mem_gb = max(1, mem // 1024)

    slurm = f"""#!/bin/bash
#SBATCH --job-name={task_id}
#SBATCH --nodes=1
#SBATCH --time={wall_h // 24}-{wall_h % 24:02d}:00:00
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task={omp}
#SBATCH --partition={partition_hint}
#SBATCH --mem={mem_gb}G
#SBATCH --no-requeue
# ROUGH TEMPLATE — HPC agent refines modules/partition based on cluster state

module purge
{module_lines}

export OMP_NUM_THREADS={omp}

cd {run_dir} && {sp.get('run_command', f'python -u {task_id}.py > pyscf.log 2>&1')}
"""

    return {
        "node_history": state.node_history + ["generate_slurm"],
        **_update_scratchpad(
            state,
            run_dir=run_dir,
            slurm_content=slurm,
            slurm_path=f"{run_dir}/pyscf_rough.sh",
        ),
    }


def pre_done(state) -> dict:
    """Write input files to disk and return artifacts to supervisor."""
    task_id = state.task_id
    sp = state.scratchpad

    # Write the Python script to disk (slurm template stays in scratchpad for HPC reference only)
    py_path = sp.get("py_path", "")
    if py_path and sp.get("py_script"):
        Path(py_path).parent.mkdir(parents=True, exist_ok=True)
        Path(py_path).write_text(sp["py_script"])

    return {
        "status": TaskStatus.DONE,
        "artifacts_out": [
            Artifact(
                artifact_id=f"{task_id}-script",
                path=sp.get("py_path", ""),
                type="gjf",
                description=f"PySCF script: {sp.get('mol', {}).get('basis', '')}",
                producer_agent="pyscf",
                producer_task_id=task_id,
            ),
            Artifact(
                artifact_id=f"{task_id}-slurm",
                path=sp.get("slurm_path", ""),
                type="slurm",
                description="Rough Slurm template for HPC refinement",
                producer_agent="pyscf",
                producer_task_id=task_id,
            ),
            Artifact(
                artifact_id=f"{task_id}-run",
                path="",
                type="json",
                description=sp.get("run_command", ""),
                producer_agent="pyscf",
                producer_task_id=task_id,
            ),
            Artifact(
                artifact_id=f"{task_id}-resources",
                path="",
                type="json",
                description=json.dumps(sp.get("resources", {}), ensure_ascii=False),
                producer_agent="pyscf",
                producer_task_id=task_id,
            ),
        ],
        "node_history": state.node_history + ["pre_done"],
    }


# ═══════════════════════════════════════════════════════════════════
# Post-computation: read
# ═══════════════════════════════════════════════════════════════════


def read_output(state) -> dict:
    """Read PySCF output log from HPC execution."""
    log_id = ""
    log_content = ""
    for ref in state.task.artifacts_in:
        if ref.type in ("log",):
            log_id = ref.artifact_id

    # In production: resolve log_id via ArtifactResolver → read file
    return {
        "node_history": state.node_history + ["read_output"],
        **_update_scratchpad(state, log_artifact_id=log_id, log_content=log_content),
    }


# ═══════════════════════════════════════════════════════════════════
# Post-computation: parse
# ═══════════════════════════════════════════════════════════════════


def parse_output(state) -> dict:
    """Parse PySCF log exhaustively using LLM."""
    from langchain_core.messages import HumanMessage, SystemMessage
    from tower.llm import get_model

    sp = state.scratchpad
    params = state.task.params
    log_content = sp.get("log_content", "")

    if not log_content:
        return {
            "result_data": PySCFResult(
                extra={"errors": ["No log content available — HPC job may not have run"]}
            ),
            "node_history": state.node_history + ["parse_output"],
        }

    prompt = PYSCF_PARSE_PROMPT.format(
        task_description=params.task_description or state.task.goal,
        expected_outputs=json.dumps(sp.get("expected_outputs", [])),
        log_content=log_content[-8000:],  # last 8k chars
    )

    try:
        model = get_model(temperature=0.0)
        response = model.invoke([
            SystemMessage(content=prompt),
            HumanMessage(content="Parse this PySCF output."),
        ])
        data = _parse_json_response(response.content)
    except Exception:
        data = {"energy": {}, "converged": {}, "extra": {"errors": ["LLM parsing failed"]}}

    # Also capture mol info from generation phase
    mol = sp.get("mol", {})
    result = PySCFResult(
        mol=mol,
        energy=data.get("energy", {}),
        converged=data.get("converged", {}),
        extra=data.get("extra", {}),
    )

    # Determine success: at least one energy value and no critical errors
    has_energy = bool(result.energy)
    critical_errors = result.extra.get("errors", [])

    status = TaskStatus.DONE
    if not has_energy and critical_errors:
        status = TaskStatus.FAILED

    return {
        "result_data": result,
        "status": status,
        "node_history": state.node_history + ["parse_output"],
    }


# ═══════════════════════════════════════════════════════════════════
# Post-computation: register artifacts
# ═══════════════════════════════════════════════════════════════════


def register_artifacts(state) -> dict:
    """Surface log artifact for downstream agents or supervisor."""
    log_id = state.scratchpad.get("log_artifact_id", "")
    artifacts = []
    if log_id:
        artifacts.append(
            Artifact(
                artifact_id=log_id,
                path="",
                type="log",
                description="PySCF output log (HPC-produced)",
                producer_agent="pyscf",
                producer_task_id=state.task_id,
                status=ArtifactStatus.READY,
            )
        )

    return {
        "status": TaskStatus.DONE,
        "artifacts_out": artifacts,
        "node_history": state.node_history + ["register_artifacts"],
    }


# ═══════════════════════════════════════════════════════════════════
# Post-computation: fix input (error correction loop)
# ═══════════════════════════════════════════════════════════════════


def fix_input(state) -> dict:
    """Analyze error and produce a corrected script.

    Increments retry counter. If retries >= MAX_RETRIES, returns NEEDS_HUMAN.
    """
    from langchain_core.messages import HumanMessage, SystemMessage
    from tower.llm import get_model

    sp = state.scratchpad
    params = state.task.params
    retries = sp.get("fix_retries", 0) + 1

    if retries >= MAX_RETRIES:
        return {
            "status": TaskStatus.NEEDS_HUMAN,
            "errors": [
                f"PySCF calculation failed after {MAX_RETRIES} correction attempts. "
                f"Last error: {sp.get('last_error', 'unknown')}"
            ],
            "node_history": state.node_history + ["fix_input"],
        }

    # Build prompt
    previous_fixes = json.dumps(sp.get("fix_history", []), indent=2)
    task_id = state.task_id
    script_path = f"jobs/{task_id}/{task_id}_fix{retries}.py"
    log_path = f"jobs/{task_id}/pyscf_fix{retries}.log"

    prompt = PYSCF_FIX_PROMPT.format(
        task_description=params.task_description or state.task.goal,
        error_category=sp.get("last_error_category", "unknown"),
        log_content=sp.get("log_content", "")[-4000:],
        current_script=sp.get("py_script", ""),
        previous_fixes=previous_fixes,
        script_path=script_path,
        log_path=log_path,
    )

    try:
        model = get_model(temperature=0.0)
        response = model.invoke([
            SystemMessage(content=prompt),
            HumanMessage(content="Fix this script."),
        ])
        data = _parse_json_response(response.content)
    except Exception:
        data = {"change_type": "needs_human", "change_description": "LLM fix failed"}

    change_type = data.get("change_type", "")

    if change_type == "needs_human":
        return {
            "status": TaskStatus.NEEDS_HUMAN,
            "errors": [data.get("change_description", "Unable to fix the calculation")],
            "node_history": state.node_history + ["fix_input"],
        }

    # Record this attempt
    fix_history = sp.get("fix_history", [])
    fix_history.append({
        "attempt": retries,
        "change_type": change_type,
        "change_description": data.get("change_description", ""),
    })

    run_command = data.get("run_command", "")
    if not run_command:
        run_command = f"python -u {task_id}.py > pyscf.log 2>&1"

    return {
        "status": TaskStatus.RETRYING,
        "retries_used": retries,
        **_update_scratchpad(
            state,
            fix_retries=retries,
            fix_history=fix_history,
            py_script=data.get("script", ""),
            py_path=script_path,
            log_path=log_path,
            run_command=run_command,
            mol=data.get("mol", sp.get("mol", {})),
            expected_outputs=data.get("expected_outputs", sp.get("expected_outputs", [])),
        ),
        "node_history": state.node_history + ["fix_input"],
    }


# ═══════════════════════════════════════════════════════════════════
# Post-computation routing helper
# ═══════════════════════════════════════════════════════════════════


def should_retry(state) -> str:
    """After parse_output: decide whether to register, fix, or give up."""
    status = state.status
    retries = state.scratchpad.get("fix_retries", 0)

    if status == TaskStatus.DONE:
        return "register"
    if status == TaskStatus.FAILED and retries < MAX_RETRIES:
        return "fix"
    return "register"  # last resort — register whatever we have
